<a href="https://colab.research.google.com/github/svlpn/ppp/blob/main/Bez_nazvania9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Обучим без нормализации и стандартизации

In [ ]:
from sklearn.datasets import load_wine
X, y = load_wine(return_X_y=True)

In [ ]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.3, random_state=42)

In [ ]:
from catboost import CatBoostClassifier
model = CatBoostClassifier()
clf = model.fit(X_train, y_train)

Learning rate set to 0.068118
0:	learn: 1.0650730	total: 58.1ms	remaining: 58.1s
1:	learn: 1.0251344	total: 58.8ms	remaining: 29.4s
2:	learn: 0.9967585	total: 59.5ms	remaining: 19.8s
3:	learn: 0.9646639	total: 60ms	remaining: 14.9s
4:	learn: 0.9376130	total: 60.6ms	remaining: 12.1s
5:	learn: 0.9055975	total: 61.2ms	remaining: 10.1s
6:	learn: 0.8728616	total: 61.7ms	remaining: 8.75s
7:	learn: 0.8394168	total: 62.1ms	remaining: 7.71s
8:	learn: 0.8186661	total: 62.6ms	remaining: 6.9s
9:	learn: 0.7955984	total: 63.1ms	remaining: 6.25s
10:	learn: 0.7734533	total: 63.6ms	remaining: 5.72s
11:	learn: 0.7509760	total: 64.1ms	remaining: 5.28s
12:	learn: 0.7305420	total: 64.7ms	remaining: 4.91s
13:	learn: 0.7077478	total: 65.1ms	remaining: 4.59s
14:	learn: 0.6819078	total: 65.7ms	remaining: 4.31s
15:	learn: 0.6577933	total: 66.2ms	remaining: 4.07s
16:	learn: 0.6334644	total: 66.7ms	remaining: 3.86s
17:	learn: 0.6097356	total: 67.1ms	remaining: 3.66s
18:	learn: 0.5899236	total: 67.7ms	remaining: 3

In [ ]:
from sklearn.metrics import roc_auc_score

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
roc_auc_score(y_test, clf.predict_proba(X_test), multi_class='ovr')

0.9943065142387036

Сделаем нормализацию

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1.5))
scaler.fit(X)
normalized_X = scaler.transform(X)
print(normalized_X)

[[1.26315789 0.28754941 0.85828877 ... 0.68292683 1.45604396 0.84201141]
 [0.85657895 0.3083004  0.62566845 ... 0.69512195 1.17032967 0.82596291]
 [0.84078947 0.48023715 1.05080214 ... 0.67073171 1.04395604 0.97039943]
 ...
 [0.88421053 1.04940711 0.72192513 ... 0.13414634 0.15934066 0.59593438]
 [0.84473684 0.54841897 0.81016043 ... 0.14634146 0.19230769 0.60128388]
 [1.22368421 0.99604743 1.10695187 ... 0.15853659 0.18131868 0.30171184]]


In [ ]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(normalized_X, y, train_size=0.3, random_state=42)


In [ ]:
from catboost import CatBoostClassifier
model = CatBoostClassifier()
clf = model.fit(X_train, y_train)
y_pred = clf.predict(X_test)


Learning rate set to 0.068118
0:	learn: 1.0650730	total: 779us	remaining: 779ms
1:	learn: 1.0251344	total: 1.5ms	remaining: 749ms
2:	learn: 0.9967585	total: 2.09ms	remaining: 695ms
3:	learn: 0.9646639	total: 2.69ms	remaining: 670ms
4:	learn: 0.9376130	total: 3.25ms	remaining: 647ms
5:	learn: 0.9055975	total: 3.83ms	remaining: 635ms
6:	learn: 0.8728616	total: 4.54ms	remaining: 644ms
7:	learn: 0.8394168	total: 5.31ms	remaining: 658ms
8:	learn: 0.8186661	total: 5.93ms	remaining: 653ms
9:	learn: 0.7955984	total: 6.5ms	remaining: 644ms
10:	learn: 0.7734533	total: 7.1ms	remaining: 638ms
11:	learn: 0.7509760	total: 7.72ms	remaining: 636ms
12:	learn: 0.7305420	total: 8.31ms	remaining: 631ms
13:	learn: 0.7077478	total: 8.87ms	remaining: 625ms
14:	learn: 0.6819078	total: 9.54ms	remaining: 626ms
15:	learn: 0.6577933	total: 10.2ms	remaining: 626ms
16:	learn: 0.6334644	total: 10.7ms	remaining: 620ms
17:	learn: 0.6097356	total: 11.1ms	remaining: 607ms
18:	learn: 0.5899236	total: 11.9ms	remaining: 61

0.9943065142387036

In [ ]:
roc_auc_score(y_test, clf.predict_proba(X_test), multi_class='ovr')

0.9943065142387036

Стандартизация

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1.5))
scaler.fit(X)
st_X = scaler.transform(X)
print(st_X)


[[1.26315789 0.28754941 0.85828877 ... 0.68292683 1.45604396 0.84201141]
 [0.85657895 0.3083004  0.62566845 ... 0.69512195 1.17032967 0.82596291]
 [0.84078947 0.48023715 1.05080214 ... 0.67073171 1.04395604 0.97039943]
 ...
 [0.88421053 1.04940711 0.72192513 ... 0.13414634 0.15934066 0.59593438]
 [0.84473684 0.54841897 0.81016043 ... 0.14634146 0.19230769 0.60128388]
 [1.22368421 0.99604743 1.10695187 ... 0.15853659 0.18131868 0.30171184]]


In [ ]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(st_X, y, train_size=0.3, random_state=42)

In [ ]:
from catboost import CatBoostClassifier
model = CatBoostClassifier()
clf = model.fit(X_train, y_train)
y_pred = clf.predict(X_test)

Learning rate set to 0.068118
0:	learn: 1.0650730	total: 1.05ms	remaining: 1.05s
1:	learn: 1.0251344	total: 1.7ms	remaining: 850ms
2:	learn: 0.9967585	total: 2.33ms	remaining: 775ms
3:	learn: 0.9646639	total: 2.98ms	remaining: 743ms
4:	learn: 0.9376130	total: 3.7ms	remaining: 736ms
5:	learn: 0.9055975	total: 4.26ms	remaining: 706ms
6:	learn: 0.8728616	total: 4.9ms	remaining: 695ms
7:	learn: 0.8394168	total: 5.53ms	remaining: 686ms
8:	learn: 0.8186661	total: 6.14ms	remaining: 676ms
9:	learn: 0.7955984	total: 6.79ms	remaining: 673ms
10:	learn: 0.7734533	total: 7.43ms	remaining: 668ms
11:	learn: 0.7509760	total: 8.01ms	remaining: 660ms
12:	learn: 0.7305420	total: 8.69ms	remaining: 660ms
13:	learn: 0.7077478	total: 9.37ms	remaining: 660ms
14:	learn: 0.6819078	total: 10ms	remaining: 660ms
15:	learn: 0.6577933	total: 10.6ms	remaining: 653ms
16:	learn: 0.6334644	total: 11.3ms	remaining: 651ms
17:	learn: 0.6097356	total: 11.7ms	remaining: 639ms
18:	learn: 0.5899236	total: 12.5ms	remaining: 647

In [ ]:
roc_auc_score(y_test, clf.predict_proba(X_test), multi_class='ovr')

0.9943065142387036

Как мы видим,  ничего не поменялось